<?xml version="1.0" encoding="UTF-8" ?>
<testsuite errors="3" failures="2" tests="6" name="tst_Xunit">
  <properties>
    <property value="4.6.0" name="QTestVersion"/>
    <property value="4.6.0" name="QtVersion"/>
  </properties>
  <testcase result="pass" name="initTestCase"/>
  <testcase result="pass" name="testFunc1">
    <error message="just a QWARN() !" type="warn"/>
  </testcase>
  <testcase result="fail" name="testFunc2">
    <error message="a qDebug() call!" type="qdebug"/>
    <failure message="Compared values are not the same
   Actual (2): 2
   Expected (3): 3" result="fail"/>
  </testcase>
  <testcase name="testFunc3">
    <error message="skipping this function!" type="skip"/>
  </testcase>
  <testcase result="fail" name="testFunc4">
    <failure message="a forced failure!" result="fail"/>
  </testcase>
  <testcase result="pass" name="cleanupTestCase"/>
</testsuite>
